// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnNJ9gBeu6EOoDXsz0eNGB1x9rWBsOeUs',
    appId: '1:79703328008:web:49a713d6dfea3c9aa2d8bd',
    messagingSenderId: '79703328008',
    projectId: 'combi-21ac9',
    authDomain: 'combi-21ac9.firebaseapp.com',
    storageBucket: 'combi-21ac9.appspot.com',
    measurementId: 'G-PDX5QCJ44C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWEk3lWn4EDNbnrjo6HwSYICYoIn0bqI',
    appId: '1:79703328008:android:d5f31e6ae31f7b51a2d8bd',
    messagingSenderId: '79703328008',
    projectId: 'combi-21ac9',
    storageBucket: 'combi-21ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm2mtgu_Ko39m1AMJViDbvtnBaLzv4J5Y',
    appId: '1:79703328008:ios:c7e4e09bb05b48bea2d8bd',
    messagingSenderId: '79703328008',
    projectId: 'combi-21ac9',
    storageBucket: 'combi-21ac9.appspot.com',
    iosBundleId: 'com.example.kombi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm2mtgu_Ko39m1AMJViDbvtnBaLzv4J5Y',
    appId: '1:79703328008:ios:c7e4e09bb05b48bea2d8bd',
    messagingSenderId: '79703328008',
    projectId: 'combi-21ac9',
    storageBucket: 'combi-21ac9.appspot.com',
    iosBundleId: 'com.example.kombi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnNJ9gBeu6EOoDXsz0eNGB1x9rWBsOeUs',
    appId: '1:79703328008:web:2e7d0f4812036852a2d8bd',
    messagingSenderId: '79703328008',
    projectId: 'combi-21ac9',
    authDomain: 'combi-21ac9.firebaseapp.com',
    storageBucket: 'combi-21ac9.appspot.com',
    measurementId: 'G-6ZJEKQKT19',
  );
}
